{%- if cookiecutter.cluster_sidecar == "yes" %}
cluster-sidecar: "slurm-sidecar.py"
{%- endif %}
cluster-cancel: "scancel"
restart-times: "{{cookiecutter.restart_times}}"
jobscript: "slurm-jobscript.sh"
cluster: "slurm-submit.py {dependencies}"
cluster-status: "slurm-status.py"
max-jobs-per-second: "{{cookiecutter.max_jobs_per_second}}"
max-status-checks-per-second: "{{cookiecutter.max_status_checks_per_second}}"
local-cores: 1
latency-wait: "{{cookiecutter.latency_wait}}"
use-conda: "{{cookiecutter.use_conda}}"
use-singularity: "{{cookiecutter.use_singularity}}"
jobs: "{{cookiecutter.jobs}}"
printshellcmds: "{{cookiecutter.print_shell_commands}}"

# Example resource configuration
# default-resources:
#   - runtime=100
#   - mem_mb=6000
#   - disk_mb=1000000
# # set-threads: map rule names to threads
# set-threads:
#   - single_core_rule=1
#   - multi_core_rule=10
# # set-resources: map rule names to resources in general
# set-resources:
#   - high_memory_rule:mem_mb=12000
#   - long_running_rule:runtime=1200
